[build]
publish = "."
command = "npm install"

[[redirects]]
from = "/*"
to = "/nolove.html"
status = 200

[build.environment]
NODE_VERSION = "18"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate" 