[build]
publish = "."
command = "echo 'No build step needed'"

[[redirects]]
from = "/"
to = "/nolove.html"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/nolove.html"
status = 200

[build.environment]
NODE_VERSION = "18"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block" 